var conteudo = document.getElementById("conteudo");
var lbl = document.createElement("label");
lbl.setAttribute("id","lbl_codigo");
conteudo.appendChild(lbl);
var input = document.createElement("input");
input.setAttribute("id","txt_codigo");
conteudo.appendChild(input);
var btn = document.createElement("button");
btn.setAttribute("id","btn_codigo");
var txt = document.createTextNode("Alterar Label");
btn.appendChild(txt);
conteudo.appendChild(btn);
var btn2 = document.createElement("button");
btn2.setAttribute("id","btn_input");
var txt2 = document.createTextNode("Alterar Input");
btn2.appendChild(txt2);
conteudo.appendChild(btn2);